// Global variables for whole engine

#import "Math";

WINDOW_TITLE_BAR : *u8 = "Longship Engine";
WINDOW_WIDTH : s32 = 1024;
WINDOW_HEIGHT : s32 = 768;

ISO_TILESET_WIDTH := 100;
ISO_TILESET_HEIGHT := 100;
ISO_TILE_WIDTH := 1.0;
ISO_TILE_HEIGHT := 1.0;
ISO_TILESET_X := -50.0;
ISO_TILESET_Z := -50.0;

X_LINE_COLOR : Vector3 = .{1.0, 0.0, 0.0};
Y_LINE_COLOR : Vector3 = .{0.0, 1.0, 0.0};
Z_LINE_COLOR : Vector3 = .{0.0, 0.0, 1.0};

